import 'package:easy_localization/easy_localization.dart';

class AppStrings {




  AppStrings._internal();

  static String translate(String word)=> word.tr();

  static const String appName = "appName";
  static const String name = "name";
  static const String loadingText = "loadingText";
  static const String streetError = "streetError";
  static const String buildingNameError = "buildingNameError";
  static const String floorError = "floorError";
  static const String apartmentNumberError = "apartmentNumberError";
  static const String imageError = "imageError";
  static const String titleError = "titleError";
  static const String descriptionError = "descriptionError";
  static const String tagsError = "tagsError";
  static const String priceError = "priceError";
  static const String nameError = "nameError";
  static const String invalidPhoneError = "invalidPhoneError";
  static const String phoneError = "phoneError";
  static const String invalidPasswordError = "invalidPasswordError";
  static const String sentCodeError = "sentCodeError";
  static const String invalidPinCodeError = "invalidPinCodeError";
  static const String notMatchPinCodeError = "notMatchPinCodeError";
  static const String forgetPassword = "forgetPassword";
  static const String selectPreferedLanguage = "selectPreferedLanguage";
  static const String haveNewOrders = "haveNewOrders";
  static const String viewOrders = "viewOrders";
  static const String deliveryTo = "deliveryTo";
  static const String searchFoodsCooks =  "searchFoodsCooks";
  static const String nearYou = "nearYou";
  static const String featuredCooks = "featuredCooks";
  static const String mostPopular = "mostPopular";
  static const String seeAll = "seeAll";
  static const String slogan = "slogan";
  static const String addFood ="addFood";
  static const String search="search";
  static const String home="home";
  static const String language="language";
  static const String categories="categories";
  static const String myProfile="myProfile";
  static const String privacy="privacy";
  static const String aboutUs="aboutUs";
  static const String settings="settings";
  static const String helpAndSupport="helpAndSupport";
  static const String saved="saved";
  static const String orders="orders";
  static const String skip="skip";
  static const String myBag="myBag";
  static const String postFood="postFood";
  static const String info="info";
  static const String sizes="sizes";
  static const String addCategories="addCategories";
  static const String description="description";
  static const String addPhotos="addPhotos";
  static const String title="title";
  static const String confirm="confirm";
  static const String addSize="addSize";
  static const String sizeDescription="sizeDescription";
  static const String price="price";
  static const String egp="egp";
  static const String male="male";
  static const String female="female";
  static const String accept="accept";
  static const String cancel="cancel";
  static const String add="add";
  static const String save="save";
  static const String edit="edit";
  static const String createAccount="createAccount";
  static const String alreadyHaveAccount="alreadyHaveAccount";
  static const String login="login";
  static const String logout="logout";
  static const String agreeSigningUp="agreeSigningUp";
  static const String phoneNumber="phoneNumber";
  static const String register="register";
  static const String password="password";
  static const String createPassword="createPassword";
  static const String verificationTitle="verificationTitle";
  static const String enterVerificationCodeMessage="enterVerificationCodeMessage";
  static const String reEnterNumberAgain="reEnterNumberAgain";
  static const String submit="submit";
  static const String didntGetCodeMessage="didntGetCodeMessage";
  static const String resend="resend";
  static const String verificationCodeExpirationTime="verificationCodeExpirationTime";
  static const String searchForAddress="searchForAddress";
  static const String confirmForDelivery="confirmForDelivery";
  static const String addressDetails="addressDetails";
  static const String useMyCurrentLocation="useMyCurrentLocation";
  static const String savedUserLocation="savedUserLocation";
  static const String selectSize="selectSize";
  static const String postedBy="postedBy";
  static const String othersBy="othersBy";
  static const String topRated="topRated";
  static const String addToCart="addToCart";
  static const String adding ="adding";
  static const String added="added";
  static const String viewBag="viewBag";
  static const String dontHaveAccount="dontHaveAccount";
  static const String signIn="signIn";
  static const String ordersHistory="ordersHistory";
  static const String savedItems="savedItems";
  static const String accountInfo="accountInfo";
  static const String languageTitle="languageTitle";
  static const String filter="filter";
  static const String filterBy="filterBy";
  static const String sorting="sorting";
  static const String type="type";
  static const String clear="clear";
}
